---
version: "3.8"
services:
  app:
    image: toy_fastapi_app:latest
    build: .
    ports:
      - 8080:8080
    environment:
      FASTAPI_APP_NATS_URLS: nats://nats:4222/
      FASTAPI_APP_REDIS_URL: redis://redis/
    depends_on:
      nats:
        condition: service_healthy
      redis:
        condition: service_healthy
      taskiq-worker:
        condition: service_started
  taskiq-worker:
    image: toy_fastapi_app:latest
    build: .
    ports: []
    environment:
      FASTAPI_APP_NATS_URLS: nats://nats:4222/
      FASTAPI_APP_REDIS_URL: redis://redis/
    depends_on:
      nats:
        condition: service_healthy
      redis:
        condition: service_healthy
    command:
      - taskiq
      - worker
      - src.app2:broker
  nats:
    image: nats:2.9.15-alpine
    hostname: nats
    command:
      - -m
      - "8222"
    healthcheck:
      test:
        - CMD
        - sh
        - -c
        - wget http://localhost:8222/healthz -q -O - | xargs | grep ok || exit 1
      interval: 5s
      timeout: 3s
      retries: 5
  redis:
    image: bitnami/redis:6.2.5
    hostname: redis
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50
